;;; Quickstart file to activate all packages at startup  -*- lexical-binding:t -*-
;; ¡¡ This file is autogenerated by `package-quickstart-refresh', DO NOT EDIT !!

(setq package--quickstart-dir
      (file-name-directory (expand-file-name load-file-name)))
(defvar package-activated-list)
(setq package-activated-list
      (delete-dups (append 'nil package-activated-list)))

;; Local Variables:
;; version-control: never
;; no-update-autoloads: t
;; byte-compile-warnings: (not make-local)
;; End:
