(require 'projectile)
(setq projectile-git-submodule-command nil)
(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
(projectile-global-mode)
;;(projectile-mode +1)
